### ISSUE TITLE
response time issue

### ISSUE THREAD

**Issue by Azharhayat271** [Achiket123/chatbot#1]
it take too much time to send the message and the response from the API is also not generating it continuously saying Gemini is thinking

**Comment by Achiket123** [comment]
sorry but my Inter exam are currently going on so i have to focus there, I will fix this issue after 9 march. Again I am sorry...!

**Comment by Chairil13** [comment]
how to navigate to login menu?

**Comment by Achiket123** [comment]
I have fixed the issues sir @Chairil13 for login menu , and Sir @Azharhayat271  Managed the response time...maybe its because of the region.
Anyways I have updated the app. And I would like you all to download and test it.
Thank You!!!
![Screenshot_1709640063](https://github.com/Achiket123/chatbot/assets/126181868/ce0133e7-4b75-4e72-b36c-5e9fd288b56b)
![Screenshot_1709665509](https://github.com/Achiket123/chatbot/assets/126181868/c4ce5a4f-c53d-477b-8968-1859bdc3b8cf)
![Screenshot_1709665537](https://github.com/Achiket123/chatbot/assets/126181868/067dfe98-4b22-4b8c-a8f3-8365c466db37)
